name: Build and deploy

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_qa_eu:
    uses: ./.github/workflows/build.yaml
    with:
      ENV: qa_eu

  build_qa_us:
    uses: ./.github/workflows/build.yaml
    with:
      ENV: qa_us

  build_stg_eu:
    uses: ./.github/workflows/build.yaml
    with:
      ENV: stg_eu

  build_stg_us:
    uses: ./.github/workflows/build.yaml
    with:
      ENV: stg_us

  #build_uat_eu:
  #  uses: ./.github/workflows/build.yaml
  #  with:
  #    ENV: uat_eu

  #build_prod_eu:
  #  uses: ./.github/workflows/build.yaml
  #  with:
  #    ENV: prod_eu

  #build_prod_us:
  #  uses: ./.github/workflows/build.yaml
  #  with:
  #    ENV: prod_us

  get_creds:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy creds
        run: |
          date
    outputs:
      DOCKER_USER: "redacted"
      DOCKER_PASS: "redacted"

  deploy_qa_eu:
    needs: [build_qa_eu, get_creds]
    uses: ./.github/workflows/deploy.yaml
    with:
      S3_BUCKET_NAME: "redacted"
      CLOUDFRONT_DISTRIBUTION_ID: "redacted"
      ARTIFACT_NAME: "webroot-qa_eu"
      DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
      DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}

  deploy_qa_us:
    needs: [build_qa_us, get_creds]
    uses: ./.github/workflows/deploy.yaml
    with:
      S3_BUCKET_NAME: "redacted"
      CLOUDFRONT_DISTRIBUTION_ID: "redacted"
      ARTIFACT_NAME: "webroot-qa_us"
      DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
      DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}

  #deploy_stg_eu:
  #  needs: [build_stg_eu, get_creds]
  #  uses: ./.github/workflows/deploy.yaml
  #  with:
  #    GITHUB_ENVIRONMENT: staging
  #    S3_BUCKET_NAME: "redacted"
  #    CLOUDFRONT_DISTRIBUTION_ID: "redacted"
  #    ARTIFACT_NAME: "webroot-stg_eu"
  #    DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
  #    DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}

  #deploy_stg_us:
  #  needs: [build_stg_us, get_creds]
  #  uses: ./.github/workflows/deploy.yaml
  #  with:
  #    GITHUB_ENVIRONMENT: staging
  #    S3_BUCKET_NAME: "redacted"
  #    CLOUDFRONT_DISTRIBUTION_ID: "redacted"
  #    ARTIFACT_NAME: "webroot-stg_us"
  #    DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
  #    DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}

  #deploy_uat_eu:
  #  needs: [build_uat_eu, get_creds]
  #  uses: ./.github/workflows/deploy.yaml
  #  with:
  #    GITHUB_ENVIRONMENT: production
  #    S3_BUCKET_NAME: "redacted"
  #    CLOUDFRONT_DISTRIBUTION_ID: "redacted"
  #    ARTIFACT_NAME: "webroot-uat_eu"
  #    DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
  #    DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}

  #deploy_prod_eu:
  #  needs: [build_prod_eu, get_creds]
  #  uses: ./.github/workflows/deploy.yaml
  #  with:
  #    GITHUB_ENVIRONMENT: production
  #    S3_BUCKET_NAME: "redacted"
  #    CLOUDFRONT_DISTRIBUTION_ID: "redacted"
  #    ARTIFACT_NAME: "webroot-prod_eu"
  #    DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
  #    DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}

  #deploy_prod_us:
  #  needs: [build_prod_us, get_creds]
  #  uses: ./.github/workflows/deploy.yaml
  #  with:
  #    GITHUB_ENVIRONMENT: production
  #    S3_BUCKET_NAME: "redacted"
  #    CLOUDFRONT_DISTRIBUTION_ID: "redacted"
  #    ARTIFACT_NAME: "webroot-prod_us"
  #    DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
  #    DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}
