name: Build and deploy

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        env: [qa_eu, qa_us, stg_eu, stg_us]
    uses: ./.github/workflows/build.yaml
    with:
      ENV: ${{ matrix.env }}

  get_creds:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy creds
        run: |
          date
    outputs:
      DOCKER_USER: "redacted"
      DOCKER_PASS: "redacted"

  deploy:
    env:
      deploy_config:
        qa_us:
          s3_bucket: b111
          cf_dist: d111
        qa_eu:
          s3_bucket: b222
          cf_dist: d222
    strategy:
      matrix:
        env: [qa_eu, qa_us, stg_eu, stg_us]
    needs: [build, get_creds]
    uses: ./.github/workflows/deploy.yaml
    with:
      ARTIFACT_NAME: "webroot-${{ matrix.env }}"
      S3_BUCKET_NAME: "${{ env.deploy_config[matrix.env].s3_bucket }}"
      CLOUDFRONT_DISTRIBUTION_ID: "${{ env.deploy_config[matrix.env].cf_dist }}"
      DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
      DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}
