name: Build and deploy

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        env: [qa_eu, qa_us, stg_eu, stg_us]
    uses: ./.github/workflows/build.yaml
    with:
      ENV: ${{ matrix.env }}

  get_creds:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy creds
        run: |
          date
    outputs:
      DOCKER_USER: "redacted"
      DOCKER_PASS: "redacted"

  deploy:
    strategy:
      matrix:
        config:
          # env, bucket_name, dist_id
          - [qa_eu, bucket-qa-eu, dist-qa-eu]
          - [qa_us, bucket-qa-us, dist-qa-us]
          - [stg_eu, bucket-stg-eu, dist-stg-eu]
          - [stg_us, bucket-stg-us, dist-stg-us]
    needs: [build, get_creds]
    uses: ./.github/workflows/deploy.yaml
    with:
      ARTIFACT_NAME: "webroot-${{ matrix.config[0] }}"
      S3_BUCKET_NAME: "${{ matrix.config[1] }}"
      CLOUDFRONT_DISTRIBUTION_ID: "${{ matrix.config[2] }}"
      DOCKER_USER: ${{ needs.get_creds.outputs.DOCKER_USER }}
      DOCKER_PASS: ${{ needs.get_creds.outputs.DOCKER_PASS }}
